# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('buttons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_button_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buttons.EmergencyButtonClient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
