db:
  image: registry.eu-gb.bluemix.net/bobvoorneveld/mariadb:latest
  ports:
    # ext:int port.
    - "3306:3306"
  environment:
    # This is obviously not a safe configuration usage in production.
    - MYSQL_DATABASE=quickly
    - MYSQL_USER=quickly
    - MYSQL_PASSWORD=quickly
    - MYSQL_ROOT_PASSWORD=quickly

web:
  image: registry.eu-gb.bluemix.net/bobvoorneveld/quicklypress_web:0.0.3
  command: python manage.py runserver 0:8000
  volumes:
    - quickly:/home/docker/
  ports:
    # ext:int port.
    - "80:8000"
  links:
    # Define all containers for easy running of development setup.
    - db
  environment:
    - DEBUG=1
    - DATABASE_URL=mysql://quickly:quickly@db/quickly
