db:
  image: mariadb:latest
  ports:
    # ext:int port.
    - "3306:3306"
  environment:
    # This is obviously not a safe configuration usage in production.
    - MYSQL_DATABASE=quickly
    - MYSQL_USER=quickly
    - MYSQL_PASSWORD=quickly
    - MYSQL_ROOT_PASSWORD=quickly

web:
  build: .
  command: python3 manage.py runserver 0:8000
  volumes:
    - .:/home/docker/quickly
  ports:
    # ext:int port.
    - "8005:8000"
  links:
    # Define all containers for easy running of development setup.
    - db
  environment:
    - DEBUG=1
    - DATABASE_URL=mysql://quickly:quickly@db/quickly
