db:
  image: mariadb:latest
  ports:
    # ext:int port.
    - "3306:3306"
  environment:
    # This is obviously not a safe configuration usage in production.
    - MYSQL_DATABASE=backend
    - MYSQL_USER=backend
    - MYSQL_PASSWORD=backend
    - MYSQL_ROOT_PASSWORD=backend

web:
  build: .
  command: python manage.py runserver 0:8000
  volumes:
    - .:/home/docker/backend
  ports:
    # ext:int port.
    - "8005:8000"
  links:
    # Define all containers for easy running of development setup.
    - db
  environment:
    - DEBUG=1
    - DATABASE_URL=mysql://backend:backend@db/backend
