# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
